---
title: "Homework 1"
author: "Abhishek Reddy Palle"
date: "11 September 2018"
output:
  word_document: default
  pdf_document: default
---

```{r}
# Generate a vector with 25 elements and each element independently follows a normal distribution (with mean =0 and sd=1)
x <- rnorm(25,0,1)
x
```

```{r}
# Reshape this vector into a 5 by 5 matrix in two ways (arranged by row and column)
a <- matrix(x, nrow = 5)
a
```

```{r}
# Similarly, generate another vector with 100 elements and plot its histogram.
b <- matrix(x, nrow = 5, byrow = T)
b
```

```{r}

# Provide screenshots of the R code used for the above questions as well as the plots in the report. Explain the plots in your own words.

hist(x)
y <- rnorm(100,0,1)
hist(y)

# Ans : The plot with 100 elements is a better representation of normal distribution compared to the one with 25 elements. As the number of samples increases, the more closely the sample probability distribution resembles the theoretical normal probability distribution.
```

```{r}

# Upload the Auto data set, which is in the ISLR library. Understand information about this data set by either ways we introduced in class (like “?Auto” and names(Auto))

library(ISLR)
?Auto
names(Auto)
```

```{r}

# Make a scatterplot between every pair of the following variables (try to plot all scatterplots in one figure; hint: use pairs() command): “mpg”, “displacement”, “horsepower”, “weight”, “acceleration”. By observing the plots, do you think the two variables in each scatterplot are correlated? If so, how? 

pairs(Auto[,c(1,3:6)])
cor(Auto[,c(1,3:6)])

#Positive Correlation means the x axis increases as the y increase approximately. In the plots displacement Vs horsepower, displacement Vs weight, horsepower vs weight are positively correlated. Negative Correlation is when one axis decreases when the other increases. In the plots mpg vs displacement, mpg Vs horsepower, mpg Vs weight are negatively correlated.
 
```

```{r}

# Draw a line on the scatterplot of mpg vs. horsepower to represent relationship between the two variables.

plot(Auto$mpg, Auto$horsepower) 
abline(lm(horsepower ~ mpg, Auto), col = "red")
lm(horsepower ~ mpg, Auto)
```


```{r}

# Is there a better way to represent their relationship rather than the linear model you just drew? (No need to use mathematical formula. Just draw something on the figure)

plot(Auto$mpg, Auto$horsepower) 
lines(lowess(Auto$mpg,Auto$horsepower), col ="red")
```







